import{a as S,S as M,i as l}from"./assets/vendor-BSTwZ_tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const y=15,q="52390417-1bf501a7c6f4bb07aa1949c3b",P=S.create({baseURL:"https://pixabay.com/api/",params:{key:q,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:y}});async function g(r,t=1){const{data:i}=await P.get("",{params:{q:r.trim(),page:t}});return i}const f=document.querySelector("#gallery"),h=document.querySelector("#load-more"),p=document.querySelector("#page-loader"),R=new M("#gallery a",{captionsData:"alt",captionDelay:250});function b(r,t=!1){const i=r.map(a=>`
<li class="gallery-item">
  <a class="gallery-link" href="${a.largeImageURL}">
    <img class="gallery-image" src="${a.webformatURL}" alt="${a.tags}" loading="lazy" />
  </a>
  <div class="gallery-info">
    <div class="gallery-info-item"><b>Likes</b>${a.likes}</div>
    <div class="gallery-info-item"><b>Views</b>${a.views}</div>
    <div class="gallery-info-item"><b>Comments</b>${a.comments}</div>
    <div class="gallery-info-item"><b>Downloads</b>${a.downloads}</div>
  </div>
</li>`).join("");t?f.insertAdjacentHTML("beforeend",i):f.innerHTML=i,R.refresh()}function B(){f.innerHTML=""}function L(){p.classList.add("active")}function v(){p.classList.remove("active")}function $(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}const w=document.querySelector(".form"),x=w.elements["search-text"],m=document.querySelector("#load-more");let n="",s=1,d=1;c();w.addEventListener("submit",A);m.addEventListener("click",E);async function A(r){if(r.preventDefault(),n=x.value.trim(),!!n){s=1,B(),c(),L();try{const{hits:t,totalHits:i}=await g(n,s);if(!Array.isArray(t)||t.length===0){l.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}d=Math.max(1,Math.ceil(i/y)),b(t,!1),s<d&&$()}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{v()}}}async function E(){if(!(s>=d)){m.disabled=!0,L();try{s+=1;const{hits:r}=await g(n,s);b(r,!0),O(),s>=d&&(c(),l.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c(),l.error({message:"Could not load more images.",position:"topRight"})}finally{v(),m.disabled=!1}}}function O(){const r=document.querySelector(".gallery .gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
